Repository aws-controllers-k8s/documentdb-controller, pull requests merged in 2024-02, with the labels that each got.

#3 Support `DBCluster` modify and tag updates
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/db_cluster.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/documentdb.services.k8s.aws_dbclusters.yaml
  config/crd/common/bases/services.k8s.aws_adoptedresources.yaml
  config/crd/common/bases/services.k8s.aws_fieldexports.yaml
  config/rbac/cluster-role-controller.yaml
  db_cluster.yaml
  generator.yaml
  go.mod
  go.sum
  helm/crds/documentdb.services.k8s.aws_dbclusters.yaml
  helm/templates/cluster-role-controller.yaml
  pkg/resource/db_cluster/custom_update.go
  pkg/resource/db_cluster/delta.go
  pkg/resource/db_cluster/hooks.go
  pkg/resource/db_cluster/references.go
  pkg/resource/db_cluster/sdk.go
  pkg/util/tags.go
  pkg/util/tags_test.go
  templates/hooks/db_cluster/sdk_create_pre_build_request.go.tpl
  templates/hooks/db_cluster/sdk_file_end.go.tpl
  templates/hooks/db_cluster/sdk_read_many_post_set_output.go.tpl
  test/e2e/resources/db_cluster.yaml
  test/e2e/tests/test_db_cluster.py
Labels: approved, lgtm

#4 Release artifact for release v0.0.1
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/zz_generated.deepcopy.go
  config/controller/kustomization.yaml
  config/crd/bases/documentdb.services.k8s.aws_dbclusters.yaml
  config/rbac/cluster-role-controller.yaml
  generator.yaml
  helm/Chart.yaml
  helm/crds/documentdb.services.k8s.aws_dbclusters.yaml
  helm/crds/services.k8s.aws_adoptedresources.yaml
  helm/crds/services.k8s.aws_fieldexports.yaml
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/caches-role-binding.yaml
  helm/templates/caches-role.yaml
  helm/templates/cluster-role-binding.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/deployment.yaml
  helm/templates/leader-election-role-binding.yaml
  helm/templates/metrics-service.yaml
  helm/templates/service-account.yaml
  helm/values.yaml
  pkg/resource/db_cluster/manager.go
Labels: approved, lgtm

#5 Generate `DBSubnetGroup` resource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/db_subnet_group.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/documentdb.services.k8s.aws_dbsubnetgroups.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/documentdb.services.k8s.aws_dbsubnetgroups.yaml
  helm/templates/_helpers.tpl
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  pkg/resource/db_cluster/delta.go
  pkg/resource/db_subnet_group/delta.go
  pkg/resource/db_subnet_group/descriptor.go
  pkg/resource/db_subnet_group/hooks.go
  pkg/resource/db_subnet_group/identifiers.go
  pkg/resource/db_subnet_group/manager.go
  pkg/resource/db_subnet_group/manager_factory.go
  pkg/resource/db_subnet_group/references.go
  pkg/resource/db_subnet_group/resource.go
  pkg/resource/db_subnet_group/sdk.go
  pkg/resource/db_subnet_group/tags.go
  templates/hooks/db_subnet_group/sdk_read_many_post_set_output.go.tpl
  templates/hooks/db_subnet_group/sdk_update_pre_set_output.go.tpl
  test/e2e/bootstrap_resources.py
  test/e2e/db_subnet_group.py
  test/e2e/replacement_values.py
  test/e2e/resources/db_subnet_group_2az.yaml
  test/e2e/service_bootstrap.py
  test/e2e/tests/test_db_subnet_group.py
Labels: approved, lgtm

#7 Generate `DBInstance` resource
  OWNERS_ALIASES
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/db_cluster.go
  apis/v1alpha1/db_instance.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/documentdb.services.k8s.aws_dbclusters.yaml
  config/crd/bases/documentdb.services.k8s.aws_dbinstances.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/documentdb.services.k8s.aws_dbclusters.yaml
  helm/crds/documentdb.services.k8s.aws_dbinstances.yaml
  helm/templates/_helpers.tpl
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  pkg/resource/db_cluster/delta.go
  pkg/resource/db_cluster/references.go
  pkg/resource/db_instance/delta.go
  pkg/resource/db_instance/descriptor.go
  pkg/resource/db_instance/hooks.go
  pkg/resource/db_instance/identifiers.go
  pkg/resource/db_instance/manager.go
  pkg/resource/db_instance/manager_factory.go
  pkg/resource/db_instance/references.go
  pkg/resource/db_instance/resource.go
  pkg/resource/db_instance/sdk.go
  pkg/resource/db_instance/tags.go
  templates/hooks/db_instance/sdk_create_post_set_output.go.tpl
  templates/hooks/db_instance/sdk_delete_pre_build_request.go.tpl
  templates/hooks/db_instance/sdk_read_many_post_set_output.go.tpl
  templates/hooks/db_instance/sdk_update_post_build_request.go.tpl
  templates/hooks/db_instance/sdk_update_post_set_output.go.tpl
  templates/hooks/db_instance/sdk_update_pre_build_request.go.tpl
  test/e2e/db_instance.py
  test/e2e/fixtures.py
  test/e2e/resources/db_instance.yaml
  test/e2e/tests/test_db_instance.py
Labels: approved, lgtm

#8 Fix DBInstance `AvailabilityZone` delta.
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/db_cluster/delta.go
  pkg/resource/db_cluster/hooks.go
  pkg/resource/db_instance/delta.go
  pkg/resource/db_instance/hooks.go
  pkg/resource/db_instance/manager.go
Labels: lgtm

#9 updating olmconfig.yaml to have proper values and examples
  olm/olmconfig.yaml
Labels: approved, ok-to-test, lgtm

#10 Release artifact for release v0.0.3
  apis/v1alpha1/ack-generate-metadata.yaml
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm
